import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { ProjectsGrid, type FilterOption } from "@/components/sections/projects-grid";
import { resolveProject } from "@/components/sections/projects";
import { Container } from "@/components/ui/section";
import {
  getUsedTags,
  projectTagLabels,
  projectsByRecency,
} from "@/lib/data/projects";
import { getDictionary, hasLocale, l, locales } from "@/lib/i18n";
import { buildMetadata, notFoundMetadata } from "@/lib/metadata";

/**
 * The full project index — the home page shows only the first six.
 *
 * `[locale]` is generated by the root layout, but this segment declares its own
 * params too so the route is prerendered for both languages rather than being
 * resolved at request time.
 */
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const dynamicParams = false;

export async function generateMetadata({
  params,
}: PageProps<"/[locale]/projects">): Promise<Metadata> {
  const { locale } = await params;
  /* Not `notFound()` — see the note on `notFoundMetadata`. */
  if (!hasLocale(locale)) return notFoundMetadata();

  const dict = getDictionary(locale);
  return buildMetadata({
    locale,
    path: "/projects",
    title: dict.projects.indexHeading,
    description: dict.projects.lede,
  });
}

export default async function ProjectsIndexPage({
  params,
}: PageProps<"/[locale]/projects">) {
  const { locale } = await params;
  if (!hasLocale(locale)) notFound();

  const dict = getDictionary(locale);

  const filters: FilterOption[] = getUsedTags().map((tag) => ({
    id: tag,
    label: l(projectTagLabels[tag], locale),
  }));

  return (
    <Container className="py-16 sm:py-20">
      {/*
        `SectionHeader` renders an <h2>, which would leave this page with no <h1>.
        The page heading is rendered here instead and the header component is used
        only for the grid's own introduction further down.
      */}
      <p
        aria-hidden
        className="text-brand-accent mb-4 flex items-center gap-3 font-mono text-xs font-medium tracking-[0.2em] uppercase"
      >
        <span className="bg-brand-accent/50 h-px w-8" />
        {dict.projects.label}
      </p>

      <h1 className="text-3xl leading-[1.1] font-semibold tracking-tight sm:text-4xl lg:text-5xl">
        {dict.projects.indexHeading}
      </h1>

      <p className="text-fg-muted mt-5 max-w-2xl text-base leading-relaxed sm:text-lg">
        {dict.projects.indexLede}
      </p>

      <div className="mt-14">
        <ProjectsGrid
          projects={projectsByRecency.map((project) =>
            resolveProject(project, locale),
          )}
          filters={filters}
        />
      </div>
    </Container>
  );
}
