import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { About } from "@/components/sections/about";
import { Contact } from "@/components/sections/contact";
import { Experience } from "@/components/sections/experience";
import { Hero } from "@/components/sections/hero";
import { Projects } from "@/components/sections/projects";
import { Skills } from "@/components/sections/skills";
import { hasLocale } from "@/lib/i18n";
import { buildMetadata, notFoundMetadata } from "@/lib/metadata";

/*
 * The locale segment's params are generated by the layout above, which is enough
 * to prerender this page for both locales — the page itself introduces no
 * dynamic segment of its own.
 */

export async function generateMetadata({
  params,
}: PageProps<"/[locale]">): Promise<Metadata> {
  const { locale } = await params;
  /* Not `notFound()` — see the note on `notFoundMetadata`. */
  if (!hasLocale(locale)) return notFoundMetadata();
  return buildMetadata({ locale });
}

export default async function HomePage({ params }: PageProps<"/[locale]">) {
  const { locale } = await params;
  if (!hasLocale(locale)) notFound();

  return (
    <>
      <Hero locale={locale} />
      <About locale={locale} />
      <Skills locale={locale} />
      <Projects locale={locale} />
      <Experience locale={locale} />
      <Contact locale={locale} />
    </>
  );
}
